apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: panzers-vm
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    jsonData:
      timeInterval: 15s
